### ISSUE TITLE
Brightness and Drawing

### ISSUE THREAD

**Issue by sanchez** [freetronics/DMD2#15]
I am implementing my own dmd library (because I am avoiding the arduino library). And I was wondering two things. Firstly if the brightness works correctly, when I attempted to do brightness I got a ghosting effect. Secondly, if I lower the refresh rate on the display, every fourth row is brighter than the previous. Is there a reason for this?
Thanks!

**Comment by sanchez** [comment]
I fixed the fourth row problem by removing continuous scanning and went with incremental scanning similar to what has been implemented here. However I still have problems with the brightness adjustment

**Comment by h4rm0n1c** [comment]
These displays are full of quirks due to their simple hardware and somewhat demanding timing requirements. My only suggestion is trial and error, that's how I got the ESP8266 support working.

Since this is not actually an issue with this library and more a request for technical info that is already available elsewhere, I'm closing this issue due to it being technically off topic.
