### ISSUE TITLE
dmd.begin() issue

### ISSUE THREAD

**Issue by najeebhall** [freetronics/DMD2#31]
I am using an arduino uno to program my p10 led board. Also i have a esp8266 connected to the arduino using softwareserial in order to send AT commands the esp8266. the wifi module is used to receive communication in the form of messages, send it to the arduino which then in turn send it to the screen. My issue is that i have noticed that when i call DMD.begin() any information received from the esp8266 after that becomes gibberish sometimes and clear sometimes (no consistency). Hence i am only able to receive one message and display on the screen. Can anyone assist with a solution to this issue? (note: calling dmd.end removes the message from the screen)

**Comment by jhonoryza** [comment]
try use hardware serial or i2c when communicating esp with uno, software serial is not reliable for now
when u use dmd.begin() the interrupt handler is on maybe that conflict with serial interupt handler

**Comment by h4rm0n1c** [comment]
Software serial likely uses timer0, so does this library.

This library cannot possibly cover all use cases, but it can provide facilities to make it easier to adapt to different use cases. For example, you can define NO_TIMERS and write your own routine to update the display.

For now, this issue is closed. If I see an opportunity to make softwareserial better coexist with this library or I'm just plain wrong about the timer0 use, I'll reopen at a later date.

**Comment by Abdalla-saad** [comment]
I have almost the same problem, I'm using SoftwareSerial which uses Timer 1, so I want to make the DMD library works without timers, I have Uncommented the " #define NO_TIMERS " in (DMD2_Timer) File.
The Code compiled successfully, but the DMD doesn't respond.
have you found a solution?

**Comment by anandrajgupta** [comment]
@Abdalla-saad, same with me!
any solution?
